import hljs from 'highlight.js/lib/core'

import javascript from 'highlight.js/lib/languages/javascript'
import typescript from 'highlight.js/lib/languages/typescript'
import python from 'highlight.js/lib/languages/python'
import java from 'highlight.js/lib/languages/java'
import go from 'highlight.js/lib/languages/go'
import rust from 'highlight.js/lib/languages/rust'
import c from 'highlight.js/lib/languages/c'
import cpp from 'highlight.js/lib/languages/cpp'
import csharp from 'highlight.js/lib/languages/csharp'
import ruby from 'highlight.js/lib/languages/ruby'
import php from 'highlight.js/lib/languages/php'
import swift from 'highlight.js/lib/languages/swift'
import kotlin from 'highlight.js/lib/languages/kotlin'
import xml from 'highlight.js/lib/languages/xml'
import css from 'highlight.js/lib/languages/css'
import sql from 'highlight.js/lib/languages/sql'
import bash from 'highlight.js/lib/languages/bash'
import json from 'highlight.js/lib/languages/json'
import yaml from 'highlight.js/lib/languages/yaml'
import markdown from 'highlight.js/lib/languages/markdown'
import diff from 'highlight.js/lib/languages/diff'
import plaintext from 'highlight.js/lib/languages/plaintext'

hljs.registerLanguage('javascript', javascript)
hljs.registerLanguage('typescript', typescript)
hljs.registerLanguage('python', python)
hljs.registerLanguage('java', java)
hljs.registerLanguage('go', go)
hljs.registerLanguage('rust', rust)
hljs.registerLanguage('c', c)
hljs.registerLanguage('cpp', cpp)
hljs.registerLanguage('csharp', csharp)
hljs.registerLanguage('ruby', ruby)
hljs.registerLanguage('php', php)
hljs.registerLanguage('swift', swift)
hljs.registerLanguage('kotlin', kotlin)
hljs.registerLanguage('html', xml) // HTML uses XML grammar
hljs.registerLanguage('xml', xml)
hljs.registerLanguage('css', css)
hljs.registerLanguage('sql', sql)
hljs.registerLanguage('bash', bash)
hljs.registerLanguage('shell', bash) // shell alias
hljs.registerLanguage('json', json)
hljs.registerLanguage('yaml', yaml)
hljs.registerLanguage('markdown', markdown)
hljs.registerLanguage('diff', diff)
hljs.registerLanguage('plaintext', plaintext)

function decodeHtmlEntities(str: string): string {
  return str
    .replace(/&amp;/g, '&')
    .replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>')
    .replace(/&quot;/g, '"')
    .replace(/&#39;/g, "'")
    .replace(/&#x27;/g, "'")
    .replace(/&#x2F;/g, '/')
}

function displayLanguageLabel(language: string): string {
  const map: Record<string, string> = {
    javascript: 'JavaScript',
    typescript: 'TypeScript',
    python: 'Python',
    java: 'Java',
    go: 'Go',
    rust: 'Rust',
    c: 'C',
    cpp: 'C++',
    csharp: 'C#',
    ruby: 'Ruby',
    php: 'PHP',
    swift: 'Swift',
    kotlin: 'Kotlin',
    html: 'HTML',
    xml: 'XML',
    css: 'CSS',
    sql: 'SQL',
    bash: 'Bash',
    shell: 'Shell',
    json: 'JSON',
    yaml: 'YAML',
    markdown: 'Markdown',
    diff: 'Diff',
    plaintext: 'Plain Text',
  }
  return map[language] ?? language
}

export function highlightCode(html: string): string {
  // Pass through pre-rendered mermaid SVG blocks (generated by admin on save)
  // Temporarily replace them with placeholders to avoid interference from the regex below
  const preRenderedBlocks: string[] = []
  let result = html.replace(
    /<div class="mermaid-pre-rendered"[^>]*>[\s\S]*?<\/div><\/div>/g,
    (match) => {
      preRenderedBlocks.push(match)
      return `\x00MERMAID_PRE_RENDERED_${preRenderedBlocks.length - 1}\x00`
    }
  )

  // Match <pre><code ...>...</code></pre> blocks and parse class attr robustly.
  // If class contains language-xxx, use that language; otherwise auto-detect.
  result = result.replace(
    /<pre><code(?:\s+class="([^"]*)")?>([\s\S]*?)<\/code><\/pre>/g,
    (_match, className: string | undefined, code: string) => {
      const lang = className?.match(/(?:^|\s)language-([a-zA-Z0-9_+-]+)(?:\s|$)/)?.[1]
      const decodedCode = decodeHtmlEntities(code).trim()

      // Skip highlighting for mermaid — render as client-side mermaid diagram
      // (only reached for old posts without pre-rendered SVGs)
      if (lang === 'mermaid') {
        const escapedCode = decodedCode.replace(/"/g, '&quot;')
        return `<div class="mermaid-source" data-mermaid="${escapedCode}" data-language="Mermaid"><div class="mermaid-loading"><span class="mermaid-loading-dot"></span><span class="mermaid-loading-dot"></span><span class="mermaid-loading-dot"></span></div><pre style="display:none"><code class="language-mermaid">${decodedCode}</code></pre></div>`
      }

      try {
        let hlResult: string
        let finalLang = lang
        if (lang && hljs.getLanguage(lang)) {
          hlResult = hljs.highlight(decodedCode, { language: lang }).value
        } else {
          // Auto-detect
          const auto = hljs.highlightAuto(decodedCode)
          hlResult = auto.value
          finalLang = auto.language
        }

        const langClass = finalLang ? ` class="language-${finalLang}"` : ''
        const langData = finalLang ? ` data-language="${displayLanguageLabel(finalLang)}"` : ''
        return `<pre${langData}><code${langClass}>${hlResult}</code></pre>`
      } catch {
        // If highlighting fails, return original with decoded entities
        const langClass = lang ? ` class="language-${lang}"` : ''
        const langData = lang ? ` data-language="${displayLanguageLabel(lang)}"` : ''
        return `<pre${langData}><code${langClass}>${decodedCode}</code></pre>`
      }
    }
  )

  // Restore pre-rendered mermaid blocks
  result = result.replace(
    /\x00MERMAID_PRE_RENDERED_(\d+)\x00/g,
    (_match, idx: string) => preRenderedBlocks[Number(idx)]
  )

  return result
}
